apiVersion: v2
name: kubeadjust
description: Lightweight Kubernetes resource limits/requests dashboard
type: application
version: 0.8.2
appVersion: "0.8.2"
keywords:
  - kubernetes
  - resources
  - dashboard
  - limits
  - requests

dependencies:
  - name: metrics-server
    version: "3.13.0"
    repository: "https://kubernetes-sigs.github.io/metrics-server/"
    condition: metrics-server.enabled
