apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeadjust.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeadjust.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "kubeadjust.name" . }}
    app.kubernetes.io/component: backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeadjust.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeadjust.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "kubeadjust.name" . }}
    app.kubernetes.io/component: frontend
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
